version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "Saturday"
      time: "10:00"
    groups:
      all-actions:
        patterns:
          - "*"
